service: relocate-v5

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  architecture: arm64
  environment:
    POSTGRES_HOST: ${env:POSTGRES_HOST, 'localhost'}
    POSTGRES_PORT: ${env:POSTGRES_PORT, '5432'}
    POSTGRES_DB: ${env:POSTGRES_DB, 'myapp'}
    POSTGRES_USER: ${env:POSTGRES_USER, 'postgres'}
    POSTGRES_PASSWORD: ${env:POSTGRES_PASSWORD, 'postgres'}
    QUEUE_ENDPOINT: ${env:QUEUE_ENDPOINT, 'http://localhost:9324'}
    QUEUE_REGION: ${env:QUEUE_REGION, 'elasticmq'}
    QUEUE_ACCESS_KEY_ID: ${env:QUEUE_ACCESS_KEY_ID, 'root'}
    QUEUE_SECRET_ACCESS_KEY: ${env:QUEUE_SECRET_ACCESS_KEY, 'root'}
    OPENAI_API_KEY: ${env:OPENAI_API_KEY}
    SERP_API_KEY: ${env:SERP_API_KEY}
    FIRECRAWL_API_KEY: ${env:FIRECRAWL_API_KEY}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - sqs:*
          Resource: "*"

functions:
  # API Gateway handlers
  topicApi:
    handler: dist/handlers/lambda/topicHandler.handler
    events:
      - httpApi:
          path: /api/topics
          method: POST

  # Queue processing handlers
  processTopic:
    handler: dist/handlers/lambda/topicHandler.handler
    reservedConcurrency: 5
    events:
      - sqs:
          arn: arn:aws:sqs:${self:provider.region}:${aws:accountId}:topic-queue
          batchSize: 1

  processQuestion:
    handler: dist/handlers/lambda/questionHandler.handler
    reservedConcurrency: 5
    events:
      - sqs:
          arn: arn:aws:sqs:${self:provider.region}:${aws:accountId}:question-queue
          batchSize: 1

  processReflection:
    handler: dist/handlers/lambda/reflectionHandler.handler
    reservedConcurrency: 5
    events:
      - sqs:
          arn: arn:aws:sqs:${self:provider.region}:${aws:accountId}:reflection-queue
          batchSize: 1

  processClarification:
    handler: dist/handlers/lambda/clarificationHandler.handler
    reservedConcurrency: 5
    events:
      - sqs:
          arn: arn:aws:sqs:${self:provider.region}:${aws:accountId}:clarification-queue
          batchSize: 1

  processQueryPreparation:
    handler: dist/handlers/lambda/queryPreparationHandler.handler
    reservedConcurrency: 5
    events:
      - sqs:
          arn: arn:aws:sqs:${self:provider.region}:${aws:accountId}:query-preparation-queue
          batchSize: 1

  processSearch:
    handler: dist/handlers/lambda/searchHandler.handler
    reservedConcurrency: 5
    events:
      - sqs:
          arn: arn:aws:sqs:${self:provider.region}:${aws:accountId}:search-queue
          batchSize: 1

  processCrawl:
    handler: dist/handlers/lambda/crawlHandler.handler
    reservedConcurrency: 5
    events:
      - sqs:
          arn: arn:aws:sqs:${self:provider.region}:${aws:accountId}:crawl-queue
          batchSize: 1

  processReview:
    handler: dist/handlers/lambda/reviewHandler.handler
    reservedConcurrency: 5
    events:
      - sqs:
          arn: arn:aws:sqs:${self:provider.region}:${aws:accountId}:review-queue
          batchSize: 1

  # Web interface
  app:
    handler: dist/app.startApplication
    events:
      - httpApi:
          path: /{proxy+}
          method: any

plugins:
  - serverless-offline-sqs
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000
    noPrependStageInUrl: true
  serverless-offline-sqs:
    autoCreate: true
    apiVersion: '2012-11-05'
    endpoint: http://0.0.0.0:9324
    region: elasticmq
    accessKeyId: root
    secretAccessKey: root
    skipCacheInvalidation: false 