service: relocate-v5

frameworkVersion: '4'

plugins:
  - serverless-offline
  - serverless-offline-sqs

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  architecture: arm64
  timeout: 30 # Default timeout for all functions
  memorySize: 1024 # Default memory for all functions
  environment:
    NODE_ENV: ${env:NODE_ENV, 'development'}
    POSTGRES_HOST: ${env:POSTGRES_HOST, 'localhost'}
    POSTGRES_PORT: ${env:POSTGRES_PORT, '5432'}
    POSTGRES_DB: ${env:POSTGRES_DB, 'myapp'}
    POSTGRES_USER: ${env:POSTGRES_USER, 'postgres'}
    POSTGRES_PASSWORD: ${env:POSTGRES_PASSWORD, 'postgres'}
    QUEUE_ENDPOINT: ${env:QUEUE_ENDPOINT, 'http://localhost:9324'}
    QUEUE_REGION: ${env:QUEUE_REGION, 'elasticmq'}
    QUEUE_ACCESS_KEY_ID: ${env:QUEUE_ACCESS_KEY_ID, 'root'}
    QUEUE_SECRET_ACCESS_KEY: ${env:QUEUE_SECRET_ACCESS_KEY, 'root'}
    OPENAI_API_KEY: ${env:OPENAI_API_KEY}
    SERP_API_KEY: ${env:SERP_API_KEY}
    FIRECRAWL_API_KEY: ${env:FIRECRAWL_API_KEY}
    S3_BUCKET: ${env:S3_BUCKET, 'socratic-learning-content'}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - sqs:*
          Resource: 
            - arn:aws:sqs:us-east-1:000000000000:topic-queue
            - arn:aws:sqs:us-east-1:000000000000:question-queue
            - arn:aws:sqs:us-east-1:000000000000:reflection-queue
            - arn:aws:sqs:us-east-1:000000000000:clarification-queue
            - arn:aws:sqs:us-east-1:000000000000:query-preparation-queue
            - arn:aws:sqs:us-east-1:000000000000:search-queue
            - arn:aws:sqs:us-east-1:000000000000:crawl-queue
            - arn:aws:sqs:us-east-1:000000000000:review-queue
            - arn:aws:sqs:us-east-1:000000000000:completed-queue
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:GetObject
            - s3:DeleteObject
          Resource: !Sub arn:aws:s3:::${self:provider.environment.S3_BUCKET}/*

functions:
  # API Gateway handler - only entry point
  studyApi:
    handler: dist/handlers/lambda/studyHandler.handler
    timeout: 10
    events:
      - httpApi:
          path: /api/study
          method: POST

  getStudiesApi:
    handler: dist/handlers/lambda/getStudiesHandler.handler
    timeout: 10
    events:
      - httpApi:
          path: /api/study
          method: GET

  getMetricsApi:
    handler: dist/handlers/lambda/metricsHandler.handler
    timeout: 10
    events:
      - httpApi:
          path: /api/metrics
          method: GET

  fireCrawlWebhook:
    handler: dist/handlers/lambda/firecrawlWebhookHandler.handler
    events:
      - http:
          path: /webhook/firecrawl
          method: post
          cors: true

  # Queue processing handlers
  processTopic:
    handler: dist/handlers/lambda/topicHandler.handler
    timeout: 30
    reservedConcurrency: 5
    events:
      - sqs:
          arn: arn:aws:sqs:us-east-1:000000000000:topic-queue
          batchSize: 1
          functionResponseType: ReportBatchItemFailures

  processQuestion:
    handler: dist/handlers/lambda/questionHandler.handler
    timeout: 30
    reservedConcurrency: 5
    events:
      - sqs:
          arn: arn:aws:sqs:us-east-1:000000000000:question-queue
          batchSize: 1
          functionResponseType: ReportBatchItemFailures

  processReflection:
    handler: dist/handlers/lambda/reflectionHandler.handler
    timeout: 30
    reservedConcurrency: 5
    events:
      - sqs:
          arn: arn:aws:sqs:us-east-1:000000000000:reflection-queue
          batchSize: 1
          functionResponseType: ReportBatchItemFailures

  processClarification:
    handler: dist/handlers/lambda/clarificationHandler.handler
    timeout: 30
    reservedConcurrency: 5
    events:
      - sqs:
          arn: arn:aws:sqs:us-east-1:000000000000:clarification-queue
          batchSize: 1
          functionResponseType: ReportBatchItemFailures

  processQueryPreparation:
    handler: dist/handlers/lambda/queryPreparationHandler.handler
    timeout: 30
    reservedConcurrency: 5
    events:
      - sqs:
          arn: arn:aws:sqs:us-east-1:000000000000:query-preparation-queue
          batchSize: 1
          functionResponseType: ReportBatchItemFailures

  processSearch:
    handler: dist/handlers/lambda/searchHandler.handler
    timeout: 30
    reservedConcurrency: 5
    events:
      - sqs:
          arn: arn:aws:sqs:us-east-1:000000000000:search-queue
          batchSize: 1
          functionResponseType: ReportBatchItemFailures

  processCrawl:
    handler: dist/handlers/lambda/crawlHandler.handler
    timeout: 60 # Longer timeout for crawling
    memorySize: 2048 # More memory for processing web content
    reservedConcurrency: 5
    events:
      - sqs:
          arn: arn:aws:sqs:us-east-1:000000000000:crawl-queue
          batchSize: 1
          functionResponseType: ReportBatchItemFailures

  processReview:
    handler: dist/handlers/lambda/reviewHandler.handler
    timeout: 60 # Longer timeout for LLM processing
    memorySize: 2048 # More memory for text processing
    reservedConcurrency: 5
    events:
      - sqs:
          arn: arn:aws:sqs:us-east-1:000000000000:review-queue
          batchSize: 1
          functionResponseType: ReportBatchItemFailures

  processCompleted:
    handler: dist/handlers/lambda/completedHandler.handler
    timeout: 30
    reservedConcurrency: 5
    events:
      - sqs:
          arn: arn:aws:sqs:us-east-1:000000000000:completed-queue
          batchSize: 1
          functionResponseType: ReportBatchItemFailures

resources:
  Resources:
    ContentBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.S3_BUCKET}
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true
        LifecycleConfiguration:
          Rules:
            - Id: DeleteOldContent
              Status: Enabled
              ExpirationInDays: 30

custom:
  serverless-offline:
    httpPort: 3000
    noPrependStageInUrl: true
  serverless-offline-sqs:
    autoCreate: true
    apiVersion: '2012-11-05'
    endpoint: http://localhost:9324
    region: elasticmq
    accessKeyId: root
    secretAccessKey: root
    skipCacheInvalidation: false
    queues:
      - topic-queue
      - question-queue
      - reflection-queue
      - clarification-queue
      - query-preparation-queue
      - search-queue
      - crawl-queue
      - review-queue
      - complete-queue 