service: relocate-v5

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  architecture: arm64
  environment:
    POSTGRES_HOST: ${env:POSTGRES_HOST, 'localhost'}
    POSTGRES_PORT: ${env:POSTGRES_PORT, '5432'}
    POSTGRES_DB: ${env:POSTGRES_DB, 'myapp'}
    POSTGRES_USER: ${env:POSTGRES_USER, 'postgres'}
    POSTGRES_PASSWORD: ${env:POSTGRES_PASSWORD, 'postgres'}
    QUEUE_ENDPOINT: ${env:QUEUE_ENDPOINT, 'http://localhost:9324'}
    QUEUE_REGION: ${env:QUEUE_REGION, 'elasticmq'}
    QUEUE_ACCESS_KEY_ID: ${env:QUEUE_ACCESS_KEY_ID, 'root'}
    QUEUE_SECRET_ACCESS_KEY: ${env:QUEUE_SECRET_ACCESS_KEY, 'root'}
    OPENAI_API_KEY: ${env:OPENAI_API_KEY}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - sqs:*
          Resource: "*"

functions:
  app:
    handler: dist/app.startApplication
    events:
      - httpApi:
          path: /{proxy+}
          method: any

plugins:
  - serverless-offline-sqs
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000
  serverless-offline-sqs:
    autoCreate: true
    apiVersion: '2012-11-05'
    endpoint: http://0.0.0.0:9324
    region: elasticmq
    accessKeyId: root
    secretAccessKey: root
    skipCacheInvalidation: false 